server:
  port: 85

spring:
  application:
    name: cloud-consumer-order

eureka:
  instance:
    instance-id: consumer-order85 #指定服务名称
    prefer-ip-address: true #显示ip
  client:
    #true 表示是否注册到注册中心 默认为true
    register-with-eureka: true
    #true 表示是否从eurekaServer抓取已有的服务信息 默认为true，单点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群 备注：实际上只需要写一个地址就可以，多个集群eureka之间会同步注册服务的信息

#设置超时
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.study.springcloud.service.PaymentFeignService: debug
