server:
  port: 85

spring:
  application:
    name: cloud-consumer-order

eureka:
  instance:
    instance-id: consumer-order85 #指定服务名称
    prefer-ip-address: true #显示ip
  client:
    #true 表示是否注册到注册中心 默认为true
    register-with-eureka: true
    #true 表示是否从eurekaServer抓取已有的服务信息 默认为true，单点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群 备注：实际上只需要写一个地址就可以，多个集群eureka之间会同步注册服务的信息

#--------------Feign负载均衡配置 配置全局超时时间
ribbon:
  ConnectTimeout: 5000 #请求连接的超时时间，默认时间为1秒
  ReadTimeout: 5000 #请求处理的超时时间

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.study.springcloud.service.OrderHystrixService: debug

# 此处是一个坑！！
# 以下两个配置需一起使用，如果feign开启了hystrix的支持，就需要在此配置默认hystrix超时时间
# 在@HystrixProperty注解中配置的时间才起作用，否则最大超时时间只能为1秒
feign:
  hystrix:
    enabled: true #开启feign的hystrix支持
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000