server:
  port: 6003

spring:
  application:
    name: cloud-payment-service-sentinel
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2022?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848 #配置nacos注册中心地址 单机
        server-addr: localhost:8845 #配置nacos注册中心地址 集群
    sentinel:
      transport:
        dashboard: localhost:8858 #配置sentinel dashboard地址
        port: 8719 #默认8719，假如端口占用会自动从8719开始一次加1，找到未占用端口
management:
  endpoints:
    web:
      exposure:
        include: "*"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.springcloud.entities
