server:
  port: 8003

spring:
  application:
    name: cloud-payment-service
  cloud:
    zookeeper:
      connect-string: zookeeper1.com:2181

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2022?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.study.springcloud.entities