FROM java:latest
ADD ./sentinel-dashboard.jar sentinel-dashboard.jar
CMD java -Dserver.port=8858 -Dcsp.sentinel.dashboard.server=localhost:8858 -Dproject.name=sentinel-dashboard -jar sentinel-dashboard.jar