version: "3"

services:
  mysql:
    container_name: nacos-mysql
    hostname: nacos-mysql
    image: mysql:5.7.33
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql/conf:/etc/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
      - ./nacos-mysql.sql:/var/nacos-mysql.sql
    restart: on-failure
    ports:
      - 3307:3306 #修改为3307，避免与本地mysql端口冲突，后面nacos配置使用真实的容器里的mysql端口，即3306，通过docker网络连接
    privileged: true
    stdin_open: true
    tty: true
    platform: linux/x86_64 #解决mac m1 环境问题
    networks:
      - nacos-net-yes

  nacos1:
    container_name: nacos-server01
    hostname: nacos-server01
    image: nacos/nacos-server:latest-slim
    environment:
      - MODE=cluster
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=nacos-mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_NAME=nacosdb
      - JVM_XMS=128m
      - JVM_XMX=128m
      - JVM_XMN=128m
    volumes:
      - ./nacos/cluster-logs/nacos-server01:/home/nacos/logs
      - ./nacos/init.d:/home/nacos/init.d
    ports:
      - 8846:8848
      - 9555:9555
    restart: on-failure
    networks:
      - nacos-net-yes

  nacos2:
    container_name: nacos-server02
    hostname: nacos-server02
    image: nacos/nacos-server:latest-slim
    environment:
      - MODE=cluster
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=nacos-mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_NAME=nacosdb
      - JVM_XMS=128m
      - JVM_XMX=128m
      - JVM_XMN=128m
    volumes:
      - ./nacos/cluster-logs/nacos-server02:/home/nacos/logs
      - ./nacos/init.d:/home/nacos/init.d
    ports:
      - 8847:8848
    restart: on-failure
    networks:
      - nacos-net-yes

  nacos3:
    container_name: nacos-server03
    hostname: nacos-server03
    image: nacos/nacos-server:latest-slim
    environment:
      - MODE=cluster
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=nacos-mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_NAME=nacosdb
      - JVM_XMS=128m
      - JVM_XMX=128m
      - JVM_XMN=128m
    volumes:
      - ./nacos/cluster-logs/nacos-server03:/home/nacos/logs
      - ./nacos/init.d:/home/nacos/init.d
    ports:
      - 8848:8848
    restart: on-failure
    networks:
      - nacos-net-yes

networks:
  nacos-net-yes:
    driver: bridge
    enable_ipv6: false
    name: "nacos-net-yes"
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16