version: "3"

services:
  mysql:
    container_name: nacos-mysql
    image: mysql:5.7.33
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql/conf:/etc/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
      - ./nacos-mysql.sql:/var/nacos-mysql.sql
    restart: on-failure
    ports:
      - 3307:3306
    privileged: true
    stdin_open: true
    tty: true