server:
  port: 9527

# 单机版本(写死url)
#spring:
#  application:
#    name: cloud-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: payment_route
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/queryById/**
#        - id: payment_route2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #开启从注册中心动态创建路由的功能，利用微服务明就行路由
      routes:
        - id: payment_route
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/queryById/**
        - id: payment_route2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

eureka:
  instance:
    instance-id: cloud-gateway-service9527 #指定服务名称
    prefer-ip-address: true #显示ip
  client:
    #true 表示是否注册到注册中心 默认为true
    register-with-eureka: true
    #true 表示是否从eurekaServer抓取已有的服务信息 默认为true，单点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群 备注：实际上只需要写一个地址就可以，多个集群eureka之间会同步注册服务的信息