server:
  port: 60

spring:
  application:
    name: cloud-consumer-order
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848 #配置nacos注册中心地址 单机
        server-addr: localhost:8845 #配置nacos注册中心地址 集群
management:
  endpoints:
    web:
      exposure:
        include: "*"