server:
  port: 60

spring:
  application:
    name: cloud-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos注册中心地址
management:
  endpoints:
    web:
      exposure:
        include: "*"